### ISSUE TITLE
Question about cljs-exif-reader date format

### ISSUE THREAD

**Issue by Jarzka** [remvee/cljs-exif-reader#1]
Hi

We are using cljs-exif-reader 0.1.0 to read metadata from JPEG photos. Here is an example result:

```
{:color-space              1
 :custom-rendered          0
 :make                     Canon�
 :iso-speed-ratings        200
 :metering-mode            5
 :resolution-unit          2
 :date-time                2018:11:21 19:39:55�
                           :date-time-original 2018:11:21 11:50:29�
 :exposure-program         3
 :aperture-value           7400879/1000000
 :focal-plane-x-resolution 56907257/32768
 :scene-capture-type       0
 :subsec-time-digitized    571�
 :date-time-digitized      2018:11:21 11:50:29�' 2018:12:15 19:48:14� '
                           :focal-length 24/1
                           :flash 16
                           :compression 6
                           :exposure-time 1/160
                           :jpeg-interchange-format 878
                           :white-balance 0
                           :max-aperture-value 4/1
                           :exposure-bias-value -2/1
                           :y-resolution 72/1
                           :shutter-speed-value 7321928/1000000
                           :exposure-mode 2
                           :jpeg-interchange-format-length 20245
                           :x-resolution 72/1
                           :subsec-time-orginal 571�
                           :focal-plane-y-resolution 56907257/32768
                           :focal-plane-resolution-unit 3
                           :software Adobe Photoshop Lightroom Classic 8.0 (Windows) �
                           :f-number 13/1
                           :model Canon EOS 6D Mark II�}
```

It seems that the date-time and date-time-original are returned in the format like `2018:11:21 11:50:29�`. I wonder what format is this and what is the last null character (\u0000) doing there? I was expecting to get something like `2018.11.21 11:50:29`.

**Comment by Jarzka** [comment]
I noticed that the value seems to be also untrimmed: " 2018:11:21 11:50:29 "

**Comment by remvee** [comment]
The null character problem was fixed in 525f165a254eb7fbeb10bd8cea110588b8672d0a but not yet release.  I've just pushed new a release; 0.2.0.  Hope that works for you.

In TIFF DateTime is encoded using colons as date separators.  See https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf section 8 for the details.

**Comment by Jarzka** [comment]
I also noticed that the date format was changed. It now returns like `"2018-11-21T09:50:29.000-00:00"`

**Comment by remvee** [comment]
True, the public API changed and yes, I should have changed the major number.  Sorry about that.  I was kinda surprised by your issue because I assumed I'm the only user of this code (using it to rotate images using orientation).

Dates should be `#inst` objects now.  See https://github.com/remvee/cljs-exif-reader/blob/master/src/remworks/exif_reader.cljc#L234 for the implementation.  Please create a new issue (preferably with a test case) when it's returns as a string.

**Comment by Jarzka** [comment]
Well, you are definitely not the only user of this library. My team is currently using it in a big Clojure project. :)

I'm not sure if the date was returned as an object or if it was only printed on the console as a string. Let's see about that. Anyway, I think we can do the upgrade with these API changes without too much effort.

**Comment by Jarzka** [comment]
I can confirm the API now returns js/Date instead of string.
